### ISSUE TITLE
Project fails on 'npx lerna bootstrap'

### ISSUE THREAD

**Issue by savenkovao** [nSoft-team/nodejs-starter#14]
npx lerna bootstrap

lerna notice cli v5.5.1
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 4 packages
artemsavenkov@MacBook-Pro-Artem servers-node % npx lerna run build
lerna notice cli v5.5.1
lerna info Executing command in 4 packages: "npm run build"
lerna ERR! npm run build exited 2 in 'base'
lerna ERR! npm run build stdout:

> base@1.0.0 build /Users/artemsavenkov/www/glassbox/servers-node/packages/base
> tsc

node_modules/sequelize-typescript/dist/associations/belongs-to-many/belongs-to-many-options.d.ts(1,68): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to-association.d.ts(1,34): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to.d.ts(1,34): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-association.d.ts(1,47): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-many.d.ts(1,32): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-one.d.ts(1,31): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/shared/association-service.d.ts(2,84): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/shared/union-association-options.d.ts(1,84): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/through/through-options.d.ts(1,56): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/hooks/shared/hook-meta.d.ts(2,32): error TS2307: Cannot find module 'sequelize/types/hooks' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/hooks/shared/hooks-service.d.ts(4,32): error TS2307: Cannot find module 'sequelize/types/hooks' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/column/attribute-service.d.ts(1,45): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/column/column.d.ts(1,55): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/index/index-service.d.ts(2,57): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-count-options.d.ts(1,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-create-options.d.ts(1,31): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-get-options.d.ts(1,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/model.d.ts(1,95): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/shared/model-service.d.ts(1,48): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/table/table-options.d.ts(1,37): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(1,58): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/scopes/scope-options.d.ts(3,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/data-type/data-type-service.d.ts(1,44): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/data-type/data-type.d.ts(1,27): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize-options.d.ts(1,25): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts(1,46): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/validation/validate.d.ts(1,38): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
src/models/user.ts(12,10): error TS2769: No overload matches this call.
  Overload 1 of 2, '(options: TableOptions<Model<any, any>>): Function', gave the following error.
    Argument of type '{ tableName: string; timestamps: boolean; }' is not assignable to parameter of type 'TableOptions<Model<any, any>>'.
      Object literal may only specify known properties, and 'tableName' does not exist in type 'TableOptions<Model<any, any>>'.
  Overload 2 of 2, '(target: Function): void', gave the following error.
    Argument of type '{ tableName: string; timestamps: boolean; }' is not assignable to parameter of type 'Function'.
      Object literal may only specify known properties, and 'tableName' does not exist in type 'Function'.
lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! base@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the base@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/artemsavenkov/.npm/_logs/2022-09-16T11_49_13_574Z-debug.log
lerna ERR! npm run build exited 2 in 'base'

node -v
v12.22.9

**Comment by nadavl** [comment]
@savenkovao can you try (with nvm or a similar tool) to up node to v16 / v18 ?

**Comment by VladislavTsygankov** [comment]
@savenkovao do u have node_modules folder in each package after `lerna bootstrap`?

**Comment by VladislavTsygankov** [comment]
Please update your node version. Node versions 10 an 12 are not supported

https://github.com/lerna/lerna/releases/tag/v5.0.0

**Comment by savenkovao** [comment]
Sounds weird , 'cause yesterday it worked

**Comment by VladislavTsygankov** [comment]
So yesterday it worked and today it's not without any changes?

**Comment by savenkovao** [comment]
No. There were changes in the starter today from your side.

Today I removed totally node_modules, pull today's changes & tried to rebuild. Error occurred

Switched to 16.X, checking

**Comment by savenkovao** [comment]
artemsavenkov@MacBook-Pro-Artem servers-node % node -v
v16.13.0


artemsavenkov@MacBook-Pro-Artem servers-node % npx lerna bootstrap
Need to install the following packages:
  lerna
Ok to proceed? (y) y
lerna notice cli v5.5.1
lerna info Bootstrapping 4 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 4 packages



artemsavenkov@MacBook-Pro-Artem servers-node % npx lerna run build
lerna notice cli v5.5.1
lerna info Executing command in 4 packages: "npm run build"
lerna ERR! npm run build exited 2 in 'base'
lerna ERR! npm run build stdout:

> base@1.0.0 build
> tsc

node_modules/sequelize-typescript/dist/associations/belongs-to-many/belongs-to-many-options.d.ts(1,68): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to-association.d.ts(1,34): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to.d.ts(1,34): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-association.d.ts(1,47): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-many.d.ts(1,32): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/has/has-one.d.ts(1,31): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/shared/association-service.d.ts(2,84): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/shared/union-association-options.d.ts(1,84): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/associations/through/through-options.d.ts(1,56): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/hooks/shared/hook-meta.d.ts(2,32): error TS2307: Cannot find module 'sequelize/types/hooks' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/hooks/shared/hooks-service.d.ts(4,32): error TS2307: Cannot find module 'sequelize/types/hooks' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/column/attribute-service.d.ts(1,45): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/column/column.d.ts(1,55): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/index/index-service.d.ts(2,57): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-count-options.d.ts(1,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-create-options.d.ts(1,31): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/association/association-get-options.d.ts(1,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/model/model.d.ts(1,95): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/shared/model-service.d.ts(1,48): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/model/table/table-options.d.ts(1,37): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(1,58): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/scopes/scope-options.d.ts(3,29): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/data-type/data-type-service.d.ts(1,44): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/data-type/data-type.d.ts(1,27): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize-options.d.ts(1,25): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts(1,46): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
node_modules/sequelize-typescript/dist/validation/validate.d.ts(1,38): error TS2307: Cannot find module 'sequelize' or its corresponding type declarations.
src/models/user.ts(12,10): error TS2769: No overload matches this call.
  Overload 1 of 2, '(options: TableOptions<Model<any, any>>): Function', gave the following error.
    Argument of type '{ tableName: string; timestamps: boolean; }' is not assignable to parameter of type 'TableOptions<Model<any, any>>'.
      Object literal may only specify known properties, and 'tableName' does not exist in type 'TableOptions<Model<any, any>>'.
  Overload 2 of 2, '(target: Function): void', gave the following error.
    Argument of type '{ tableName: string; timestamps: boolean; }' is not assignable to parameter of type 'Function'.
      Object literal may only specify known properties, and 'tableName' does not exist in type 'Function'.
lerna ERR! npm run build exited 2 in 'base'
artemsavenkov@MacBook-Pro-Artem servers-node %

**Comment by savenkovao** [comment]
Cleared again, stopped & removed all containers.
node -v 16.13.0

Working now

**Comment by savenkovao** [comment]
not it fixed, thanks!
