### ISSUE TITLE
Service is down after starting project in different folder

### ISSUE THREAD

**Issue by savenkovao** [nSoft-team/nodejs-starter#17]
I copied the content of the starter project into our repo & tried to raise the app. 
Does not work

faced only issue in build log:
![image](https://user-images.githubusercontent.com/20910231/190659658-c798a60f-8e6c-4d74-ab5b-8b40684c6c93.png)
![image](https://user-images.githubusercontent.com/20910231/190659665-91005160-9581-4e21-a7aa-20be8726f54c.png)

**Comment by savenkovao** [comment]
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
worker           |            ^
kafka_1          | [main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - An exception was thrown while closing send thread for session 0x1000147d7aa0000.
kafka_1          | EndOfStreamException: Unable to read additional data from server sessionid 0x1000147d7aa0000, likely server has closed socket
kafka_1          |      at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
kafka_1          |      at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
kafka_1          |      at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
worker           | TSError: ⨯ Unable to compile TypeScript:
worker           | src/index.ts(12,21): error TS2339: Property 'authenticate' does not exist on type 'Sequelize'.
worker           | src/index.ts(15,21): error TS2339: Property 'sync' does not exist on type 'Sequelize'.
worker           | 
worker           |     at createTSError (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:859:12)
worker           |     at reportTSError (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:863:19)
worker           |     at getOutput (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1077:36)
worker           |     at Object.compile (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1433:41)
worker           |     at Module.m._compile (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1617:30)
worker           |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
worker           |     at Object.require.extensions.<computed> [as .ts] (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1621:12)
worker           |     at Module.load (node:internal/modules/cjs/loader:997:32)
worker           |     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
worker           |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
worker           |   diagnosticCodes: [ 2339, 2339 ]
worker           | }
user             | /glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:859
user             |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
user             |            ^
user             | TSError: ⨯ Unable to compile TypeScript:
user             | src/index.ts(13,14): error TS2339: Property 'authenticate' does not exist on type 'Sequelize'.
user             | src/index.ts(14,14): error TS2339: Property 'sync' does not exist on type 'Sequelize'.
user             | 
user             |     at createTSError (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:859:12)
user             |     at reportTSError (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:863:19)
user             |     at getOutput (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1077:36)
user             |     at Object.compile (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1433:41)
user             |     at Module.m._compile (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1617:30)
user             |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
user             |     at Object.require.extensions.<computed> [as .ts] (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1621:12)
user             |     at Module.load (node:internal/modules/cjs/loader:997:32)
user             |     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
user             |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
user             |   diagnosticCodes: [ 2339, 2339 ]
user             | }
kafka_1          | [main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x1000147d7aa0000
kafka_1          | [main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x1000147d7aa0000 closed
cassandra        | INFO  [main] 2022-09-16 14:05:50,941 Keyspace.java:386 - Creating replication strategy system params KeyspaceParams{durable_writes=true, replication=ReplicationParams{class=org.apache.cassandra.locator.LocalStrategy}}
worker           | [nodemon] app crashed - waiting for file changes before starting...
user             | [nodemon] app crashed - waiting for file changes before starting...
cassandra        | INFO  [main] 2022-09-16 14:05:51,120 ColumnFamilyStore.java:385 - Initializing system.IndexInfo
kafka_1          | ===> Launching ... 
kafka_1          | ===> Launching kafka ... 
cassandra-web    | Error: Cannot find module 'reflect-metadata'
cassandra-web    | Require stack:
cassandra-web    | - /glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/associations/shared/association-service.js
cassandra-web    | - /glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to.js
cassandra-web    | - /glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/index.js
cassandra-web    | - /glassbox-ms/packages/base/dist/models/user.js
cassandra-web    | - /glassbox-ms/packages/base/dist/models/index.js
cassandra-web    | - /glassbox-ms/packages/base/dist/index.js
cassandra-web    | - /glassbox-ms/packages/cassandra-web/src/app.ts
cassandra-web    | - /glassbox-ms/packages/cassandra-web/src/index.ts
cassandra-web    |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
cassandra-web    |     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/glassbox-ms/packages/cassandra-web/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
cassandra-web    |     at Function.Module._load (node:internal/modules/cjs/loader:803:27)
cassandra-web    |     at Module.require (node:internal/modules/cjs/loader:1021:19)
cassandra-web    |     at require (node:internal/modules/cjs/helpers:103:18)
cassandra-web    |     at Object.<anonymous> (/glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/associations/shared/association-service.js:4:1)
cassandra-web    |     at Module._compile (node:internal/modules/cjs/loader:1119:14)
cassandra-web    |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
cassandra-web    |     at Object.require.extensions.<computed> [as .js] (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:1608:43)
cassandra-web    |     at Module.load (node:internal/modules/cjs/loader:997:32) {
cassandra-web    |   code: 'MODULE_NOT_FOUND',
cassandra-web    |   requireStack: [
cassandra-web    |     '/glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/associations/shared/association-service.js',
cassandra-web    |     '/glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/associations/belongs-to/belongs-to.js',
cassandra-web    |     '/glassbox-ms/packages/base/node_modules/sequelize-typescript/dist/index.js',
cassandra-web    |     '/glassbox-ms/packages/base/dist/models/user.js',
cassandra-web    |     '/glassbox-ms/packages/base/dist/models/index.js',
cassandra-web    |     '/glassbox-ms/packages/base/dist/index.js',
cassandra-web    |     '/glassbox-ms/packages/cassandra-web/src/app.ts',
cassandra-web    |     '/glassbox-ms/packages/cassandra-web/src/index.ts'
cassandra-web    |   ]
cassandra-web    | }
cassandra-web    | [nodemon] app crashed - waiting for file changes before starting...
kafka_1          | [2022-09-16 14:05:52,218] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_ui_1       | 2022-09-16 14:05:52,287 INFO  [main] o.s.d.r.c.RepositoryConfigurationDelegate: Bootstrapping Spring Data LDAP repositories in DEFAULT mode.
kafka_ui_1       | 2022-09-16 14:05:52,354 INFO  [main] o.s.d.r.c.RepositoryConfigurationDelegate: Finished Spring Data repository scanning in 58 ms. Found 0 LDAP repository interfaces.
kafka_1          | [2022-09-16 14:05:52,539] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
kafka_1          | [2022-09-16 14:05:52,694] INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler)
kafka_1          | [2022-09-16 14:05:52,698] INFO starting (kafka.server.KafkaServer)
kafka_1          | [2022-09-16 14:05:52,698] INFO Connecting to zookeeper on zookeeper:2181 (kafka.server.KafkaServer)
kafka_1          | [2022-09-16 14:05:52,724] INFO [ZooKeeperClient Kafka server] Initializing a new session to zookeeper:2181. (kafka.zookeeper.ZooKeeperClient)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:zookeeper.version=3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a, built on 04/08/2021 16:35 GMT (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:host.name=873789f9a08f (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.version=11.0.15 (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.vendor=Azul Systems, Inc. (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.home=/usr/lib/jvm/zulu11-ca (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.class.path=/usr/bin/../share/java/kafka/jersey-container-servlet-core-2.34.jar:/usr/bin/../share/java/kafka/netty-buffer-4.1.73.Final.jar:/usr/bin/../share/java/kafka/jakarta.ws.rs-api-2.1.6.jar:/usr/bin/../share/java/kafka/kafka-storage-api-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/netty-handler-4.1.73.Final.jar:/usr/bin/../share/java/kafka/scala-java8-compat_2.13-1.0.2.jar:/usr/bin/../share/java/kafka/connect-transforms-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jakarta.inject-2.6.1.jar:/usr/bin/../share/java/kafka/aopalliance-repackaged-2.6.1.jar:/usr/bin/../share/java/kafka/jackson-core-2.13.2.jar:/usr/bin/../share/java/kafka/jetty-security-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/rocksdbjni-6.29.4.1.jar:/usr/bin/../share/java/kafka/hk2-locator-2.6.1.jar:/usr/bin/../share/java/kafka/jetty-servlet-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/jersey-client-2.34.jar:/usr/bin/../share/java/kafka/hk2-utils-2.6.1.jar:/usr/bin/../share/java/kafka/netty-resolver-4.1.73.Final.jar:/usr/bin/../share/java/kafka/kafka-shell-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/zstd-jni-1.5.2-1.jar:/usr/bin/../share/java/kafka/kafka-metadata-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jackson-databind-2.13.2.2.jar:/usr/bin/../share/java/kafka/connect-mirror-client-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jersey-hk2-2.34.jar:/usr/bin/../share/java/kafka/kafka-clients-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jackson-annotations-2.13.2.jar:/usr/bin/../share/java/kafka/netty-transport-native-unix-common-4.1.73.Final.jar:/usr/bin/../share/java/kafka/kafka-log4j-appender-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jakarta.activation-api-1.2.2.jar:/usr/bin/../share/java/kafka/jackson-datatype-jdk8-2.13.2.jar:/usr/bin/../share/java/kafka/paranamer-2.8.jar:/usr/bin/../share/java/kafka/jackson-module-jaxb-annotations-2.13.2.jar:/usr/bin/../share/java/kafka/trogdor-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/netty-tcnative-classes-2.0.46.Final.jar:/usr/bin/../share/java/kafka/commons-lang3-3.8.1.jar:/usr/bin/../share/java/kafka/kafka_2.13-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jetty-io-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/jakarta.validation-api-2.0.2.jar:/usr/bin/../share/java/kafka/netty-transport-classes-epoll-4.1.73.Final.jar:/usr/bin/../share/java/kafka/reflections-0.9.12.jar:/usr/bin/../share/java/kafka/slf4j-reload4j-1.7.36.jar:/usr/bin/../share/java/kafka/scala-library-2.13.8.jar:/usr/bin/../share/java/kafka/maven-artifact-3.8.4.jar:/usr/bin/../share/java/kafka/jetty-servlets-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/connect-basic-auth-extension-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jackson-module-scala_2.13-2.13.2.jar:/usr/bin/../share/java/kafka/jackson-jaxrs-base-2.13.2.jar:/usr/bin/../share/java/kafka/jakarta.xml.bind-api-2.3.3.jar:/usr/bin/../share/java/kafka/javassist-3.27.0-GA.jar:/usr/bin/../share/java/kafka/connect-api-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jose4j-0.7.9.jar:/usr/bin/../share/java/kafka/jetty-continuation-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/kafka-streams-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jetty-http-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/snappy-java-1.1.8.4.jar:/usr/bin/../share/java/kafka/netty-transport-native-epoll-4.1.73.Final.jar:/usr/bin/../share/java/kafka/jetty-util-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/scala-collection-compat_2.13-2.6.0.jar:/usr/bin/../share/java/kafka/zookeeper-3.6.3.jar:/usr/bin/../share/java/kafka/commons-cli-1.4.jar:/usr/bin/../share/java/kafka/hk2-api-2.6.1.jar:/usr/bin/../share/java/kafka/jersey-common-2.34.jar:/usr/bin/../share/java/kafka/jakarta.annotation-api-1.3.5.jar:/usr/bin/../share/java/kafka/argparse4j-0.7.0.jar:/usr/bin/../share/java/kafka/lz4-java-1.8.0.jar:/usr/bin/../share/java/kafka/jline-3.21.0.jar:/usr/bin/../share/java/kafka/jaxb-api-2.3.0.jar:/usr/bin/../share/java/kafka/kafka-tools-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/kafka-streams-examples-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/scala-reflect-2.13.8.jar:/usr/bin/../share/java/kafka/connect-json-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/kafka-raft-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/zookeeper-jute-3.6.3.jar:/usr/bin/../share/java/kafka/jackson-dataformat-csv-2.13.2.jar:/usr/bin/../share/java/kafka/javax.servlet-api-3.1.0.jar:/usr/bin/../share/java/kafka/netty-transport-4.1.73.Final.jar:/usr/bin/../share/java/kafka/audience-annotations-0.5.0.jar:/usr/bin/../share/java/kafka/jersey-server-2.34.jar:/usr/bin/../share/java/kafka/reload4j-1.2.19.jar:/usr/bin/../share/java/kafka/jackson-jaxrs-json-provider-2.13.2.jar:/usr/bin/../share/java/kafka/jetty-util-ajax-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/kafka.jar:/usr/bin/../share/java/kafka/jopt-simple-5.0.4.jar:/usr/bin/../share/java/kafka/metrics-core-2.2.0.jar:/usr/bin/../share/java/kafka/connect-runtime-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jetty-client-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/kafka-server-common-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/osgi-resource-locator-1.0.3.jar:/usr/bin/../share/java/kafka/javax.ws.rs-api-2.1.1.jar:/usr/bin/../share/java/kafka/netty-common-4.1.73.Final.jar:/usr/bin/../share/java/kafka/scala-logging_2.13-3.9.4.jar:/usr/bin/../share/java/kafka/activation-1.1.1.jar:/usr/bin/../share/java/kafka/jetty-server-9.4.44.v20210927.jar:/usr/bin/../share/java/kafka/connect-mirror-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/metrics-core-4.1.12.1.jar:/usr/bin/../share/java/kafka/slf4j-api-1.7.36.jar:/usr/bin/../share/java/kafka/kafka-streams-scala_2.13-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/kafka-storage-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/jersey-container-servlet-2.34.jar:/usr/bin/../share/java/kafka/kafka-streams-test-utils-7.2.1-ccs.jar:/usr/bin/../share/java/kafka/netty-codec-4.1.73.Final.jar:/usr/bin/../share/java/kafka/plexus-utils-3.3.0.jar:/usr/bin/../share/java/confluent-telemetry/* (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.library.path=/usr/java/packages/lib:/lib:/usr/lib:/usr/lib64:/lib64 (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
kafka_1          | [2022-09-16 14:05:52,729] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)

**Comment by nadavl** [comment]
@savenkovao what do you mean by _your repo?_
How is it different to this repo?

The starter is built to work as a monorepo (this repo) with these packages and config exactly.
Adding it / part of it to an existing repo might require config modifications to be made.

**Comment by nadavl** [comment]
Specifically in your TS Error, I see Sequelize types missing.

**Comment by savenkovao** [comment]
Our private repository in Bitbucket.

No difference, same content.
ATM I run it locally, so I guess should not be difference, right?
![image](https://user-images.githubusercontent.com/20910231/190663969-b97baf8f-8a11-49fd-b1cf-44651d370524.png)

**Comment by savenkovao** [comment]
> 

What should I do with it?

Already tried to delete all node_modules/package-lock(s)/dists & rerun from scratch:

npx lerna bootstrap
npx lerna run build
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

Issue remain
![image](https://user-images.githubusercontent.com/20910231/190665554-de2b7dfb-fb57-4fb9-86da-80cbdec5352b.png)

**Comment by nadavl** [comment]
Yeah nothing is supposed to change, unless locally you're now using another node ver or something.
I also cannot help much as I don't have access to your bitbucket. But really it shouldn't matter unless the repo created with BB has some default configs which collide.

What happens when you clone the **original starter repo** into your machine (into a new folder) and run it?
If something broke, it'll show up at that point.

**Comment by savenkovao** [comment]
Working OK if I start it from the starter.

weird, I changed nothing. Even compared package-locks, they are identical
node 16.13.0
![image](https://user-images.githubusercontent.com/20910231/190681655-7592b4cd-0c7d-441c-b992-8691fda77d8e.png)
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/20910231/190681671-2c904bd0-feb2-4599-a70d-ca018e97ce01.png">

**Comment by savenkovao** [comment]
I ensured, that our project uses the same files.

node v 16.13.0

No errors running
```
npx lerna bootstrap
npx lerna run build
```

Raising project with
docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

Still error with Sequelize

Then if I stop, remove containers & try to raise the project from the starter - no errors.
Both repositories are in the same folder.

Since I run in development mode, the issue also appears after changing ts files in /packages


![image](https://user-images.githubusercontent.com/20910231/190686810-91ac2797-7cc2-4c9c-a0eb-c539c4b4e078.png)
![image](https://user-images.githubusercontent.com/20910231/190686827-63ee8af9-208f-4d37-8c70-314e637f45e7.png)
![image](https://user-images.githubusercontent.com/20910231/190686834-9a90ffec-4a32-477d-86c3-cd7f4c710fe1.png)
![image](https://user-images.githubusercontent.com/20910231/190686839-ef791735-9ad2-4ba5-bcf4-38d4c9c883b9.png)

![image](https://user-images.githubusercontent.com/20910231/190687194-e4f586e6-28c4-49e3-a953-2cae3381a02d.png)

**Comment by nadavl** [comment]
Got it.

I'm not sure what's on the other repo and what could collide. Pretty
impossible to debug without access to it.

What version of lerna is running in the other repo?

**Comment by savenkovao** [comment]
Starter
![image](https://user-images.githubusercontent.com/20910231/190991694-aef33b54-10c9-4db9-a91e-05db6c4509c7.png)


Our repo
![image](https://user-images.githubusercontent.com/20910231/190991963-ae3ef62f-498c-42a0-b1be-1534fbe7cde1.png)

**Comment by savenkovao** [comment]
Could we have call with you today, please?

**Comment by savenkovao** [comment]
Container logs:

![Screenshot 2022-09-19 at 16 51 25](https://user-images.githubusercontent.com/20910231/191033326-fa02789d-104b-4bb0-be6e-3cf6725f2bb0.png)
![image](https://user-images.githubusercontent.com/20910231/191033545-26afc15f-09a9-4cd0-a871-fb5964ccc47e.png)
![image](https://user-images.githubusercontent.com/20910231/191033691-e50f39fa-8fcd-48e3-90e4-520b5e00a159.png)
